/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hussein_pc
 */
public class Bre_table extends javax.swing.JPanel {

    int xi, yi, xf, yf, dx, dy, xtr, ytr, pk, xs, ys, pkk;
    float m;
    int k;

    /**
     * Creates new form Tabel1
     */
    public Bre_table() {
        initComponents();
    }

    public void cre_tabel(int Xi, int Yi, int Xf, int Yf) {

        DefaultTableModel object1 = (DefaultTableModel) Bre_tabel.getModel();
        this.xi = Xi;
        this.yi = Yi;
        this.xf = Xf;
        this.yf = Yf;
        int dx = xf - xi;
        int dy = yf - yi;

        k = 0;
        if (dy < dx) {
            pk = (2 * dy) - dx;
            for (int i = 0; i < dx; i++) {

               if (pk < 0) {
                    xi++;
                    pkk = pk + (2 * dy);
                    object1.addRow(new Object[]{k, pk, pkk, xi, yi});
                    pk = pkk;
                    k++;

                } else {


                    xi++;
                    yi++;
                    pkk = pk + (2 * dy) - (2 * dx);
                    object1.addRow(new Object[]{k, pk, pkk, xi, yi});
                    pk = pkk;

                    k++;
                }
                 
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Bre_tabel = new javax.swing.JTable();

        Bre_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "K", "Pk", "Pk+1", "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(Bre_tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Bre_tabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
