/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Graphics;

/**
 *
 * @author ahmed
 */
public class drawellipse extends javax.swing.JPanel {

    int x, y, p01, p02, p1k, p1kk, p2k, p2kk, ryx, rxy, ry, rx, xcen, ycen;
    int xval, yval;

    
    public drawellipse() {
        initComponents();
        setSize(460, 486);
        setVisible(false);
        
    }

    public void takevalue(int x, int y, int rx, int ry) {
        this.xval = x;
        this.yval = y;
        this.rx = rx;
        this.ry = ry;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawLine(getWidth() / 2, 0, getWidth() / 2, getHeight());
        g.drawLine(0, getHeight() / 2, getWidth(), getHeight() / 2);
        x = 0;
        y = ry;
        p01 = (int) (.25 * Math.pow(rx, 2) - (Math.pow(rx, 2) * ry) + Math.pow(ry, 2));
        p1k = p01;
        do {
            //to transfer to first quarter it is asame in java fourth quarter
            g.drawLine(xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 - y), xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 - y));
            g.drawLine(xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 + y), xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 + y));
            // to transfer to second quarter it is asame in java third quarter
            g.drawLine(xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 - y), xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 - y));
            g.drawLine(xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 + y), xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 + y));

            x++;
            if (p1k < 0) {
                ryx = (int) (Math.pow(ry, 2) * x);
                rxy = (int) (Math.pow(rx, 2) * y);
                p1kk = (int) (p1k + (2 * Math.pow(ry, 2) * x) + Math.pow(ry, 2));
                p1k = p1kk;
            } else {
                y--;
                ryx = (int) (Math.pow(ry, 2) * x);
                rxy = (int) (Math.pow(rx, 2) * y);
                p1kk = (int) (p1k + (2 * Math.pow(ry, 2) * x) + Math.pow(ry, 2) - (2 * Math.pow(rx, 2) * y));
                p1k = p1kk;
            }
            //repaint();
        } while (ryx <= rxy);
        System.out.println(x + " || " + y);
        p02 = (int) (Math.pow(ry, 2) * Math.pow((x + .5), 2) + Math.pow(rx, 2) * Math.pow((y - 1), 2) - Math.pow(rx, 2) * Math.pow(ry, 2));
        p2k = p02;
        do {

            //to transfer to third quarter it is asame in java second quarter
            g.drawLine(xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 + y), xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 + y));
            g.drawLine(xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 - y), xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 - y));
            //to transfer to fouth quarter it is asame in java first quarter
            g.drawLine(xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 + y), xval + (getWidth() / 2 + x), -yval + (getHeight() / 2 + y));
            g.drawLine(xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 - y), xval + (getWidth() / 2 - x), -yval + (getHeight() / 2 - y));
            y--;
            if (p2k < 0) {

                x++;
                ryx = (int) Math.pow(ry, 2) * x;
                rxy = (int) Math.pow(rx, 2) * y;
                p2kk = (int) (p2k + (2 * Math.pow(ry, 2) * x) - (2 * Math.pow(rx, 2) * y) + Math.pow(rx, 2));
                p2k = p2kk;

            } else {
                ryx = (int) Math.pow(ry, 2) * x;
                rxy = (int) Math.pow(rx, 2) * y;
                p2kk = (int) (p2k - (2 * Math.pow(rx, 2) * y) + Math.pow(rx, 2));
                p2k = p2kk;
            }
        } while (rxy > 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
